import type { Exercise } from '../types/db';

export const SEED_EXERCISES: Omit<Exercise, 'id'>[] = [
  { name: 'Bench Press', muscle: 'Chest' },
  { name: 'Incline Press', muscle: 'Chest' },
  { name: 'Dumbbell Press', muscle: 'Chest' },
  { name: 'Chest Fly', muscle: 'Chest' },
  { name: 'Squat', muscle: 'Legs' },
  { name: 'Leg Press', muscle: 'Legs' },
  { name: 'Lunge', muscle: 'Legs' },
  { name: 'Step Up', muscle: 'Legs' },
  { name: 'Deadlift', muscle: 'Back' },
  { name: 'Pull-up', muscle: 'Back' },
  { name: 'Barbell Row', muscle: 'Back' },
  { name: 'Lat Pulldown', muscle: 'Back' },
  { name: 'Cable Row', muscle: 'Back' },
  { name: 'Romanian Deadlift', muscle: 'Hamstrings' },
  { name: 'Leg Curl', muscle: 'Hamstrings' },
  { name: 'Leg Extension', muscle: 'Quads' },
  { name: 'Calf Raise', muscle: 'Calves' },
  { name: 'Overhead Press', muscle: 'Shoulders' },
  { name: 'Face Pull', muscle: 'Shoulders' },
  { name: 'Lateral Raise', muscle: 'Shoulders' },
  { name: 'Front Raise', muscle: 'Shoulders' },
  { name: 'Dumbbell Curl', muscle: 'Biceps' },
  { name: 'Hammer Curl', muscle: 'Biceps' },
  { name: 'Tricep Pushdown', muscle: 'Triceps' },
  { name: 'Skull Crusher', muscle: 'Triceps' },
  { name: 'Hip Thrust', muscle: 'Glutes' },
  { name: 'Plank', muscle: 'Core' },
  { name: 'Crunch', muscle: 'Core' },
  { name: 'Russian Twist', muscle: 'Core' },
  { name: 'Mountain Climber', muscle: 'Core' },
];
